import { PricingPlan } from "@/components/pricing-plans";

export const pricingPlans: PricingPlan[] = [
  {
    name: "Free",
    price: "$0",
    period: "/month",
    description: "Perfect for getting started",
    features: [
      "Up to 1,000 requests/month",
      "Basic API access",
      "Community support",
      "Standard documentation",
      "99% uptime SLA",
      "1 project",
      "Email notifications",
    ],
    highlighted: false,
    cta: "Get Started Free",
    ctaVariant: "outline-primary",
  },
  {
    name: "Basic",
    price: "$29",
    period: "/month",
    description: "For growing businesses",
    features: [
      "Up to 50,000 requests/month",
      "Full API access",
      "Email support",
      "Advanced analytics",
      "99.5% uptime SLA",
      "5 projects",
      "Priority email support",
      "Custom integrations",
      "API rate limit: 10 req/sec",
    ],
    highlighted: true,
    cta: "Start Free Trial",
    ctaVariant: "primary",
  },
  {
    name: "Pro",
    price: "$99",
    period: "/month",
    description: "For teams and scale",
    features: [
      "Up to 500,000 requests/month",
      "Full API access",
      "Priority support",
      "Advanced analytics & reporting",
      "99.9% uptime SLA",
      "Unlimited projects",
      "24/7 priority support",
      "Custom integrations",
      "API rate limit: 100 req/sec",
      "Dedicated account manager",
      "Custom SLA options",
    ],
    highlighted: false,
    cta: "Start Free Trial",
    ctaVariant: "primary",
  },
];
